# Site settings
author: Kat Tochowicz
title: Kat Codes
header-img: img/home-bg.png
email: ktochow1@binghamton.edu
copyright_name: Kat Tochowicz
description: > # this means to ignore newlines until "baseurl:"
  Learning how to code one byte at a time. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ktochow1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
